{% set name = "wwt_api_client" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wwt_api_client-{{ version }}.tar.gz
  sha256: 51c9b91f2b097ddc261388ff60a8e88de9779a5e3ecd9e052626ed7c46129306

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dataclasses-json >=0.5
    - openidc_client >=0.6
    - requests >=2.10
    - wwt_data_formats >=0.16

test:
  imports:
    - wwt_api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WorldWideTelescope/wwt_api_client
  summary: An API client for the AAS WorldWide Telescope web services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
